apiVersion: v2
name: openfga
description: A Kubernetes Helm chart for the OpenFGA project.

type: application
version: 0.1.1
appVersion: "v0.3.6"

home: "https://openfga.github.io/helm-charts/charts/openfga"

annotations:
  artifacthub.io/license: Apache-2.0

dependencies:
  - name: postgresql
    version: "12.2.3"
    repository: https://charts.bitnami.com/bitnami
    condition: postgres.enabled
  - name: mysql
    version: "9.6.0"
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
